puts "Deleting old seeds..."
Citizen.destroy_all
Note.destroy_all
Category.destroy_all
User.destroy_all

puts "Creating a new user..."
user = User.create!(
  name: "user",
  email: "email@email.com",
  password: "111111",
  map_size: "large"
)

user.tile_map = [
  ["base",
  "city_road_v",
  "tree_grove",
  "tree_grove",
  "poplar_tree",
  "base",
  "poplar_tree",
  "base",
  "city_road_v",
  "base",
  "base",
  "city_road_v",
  "base",
  "base",
  "base"],

  ["city_road_h",
  "city_tcross_south",
  "tree_grove",
  "base",
  "poplar_tree",
  "base",
  "base",
  "base",
  "city_road_v",
  "base",
  "base",
  "city_tcross_north",
  "city_road_h",
  "city_road_h",
  "city_road_h"],

  ["base",
  "city_road_v",
  "park_trees",
  "cobblestone",
  "park_trees",
  "city_turn_nw",
  "city_road_h",
  "city_road_h",
  "city_tcross_west",
  "city_turn_ne",
  "base",
  "city_road_v",
  "base",
  "base",
  "base"],

  ["park_trees",
  "city_road_v",
  "cobblestone",
  "base",
  "cobblestone",
  "city_road_v",
  "base",
  "wild_grove",
  "wild_grove",
  "city_road_v",
  "base",
  "city_road_v",
  "base",
  "cobblestone",
  "base"],

  ["base",
  "city_tcross_north",
  "city_road_h",
  "city_road_h",
  "city_road_h",
  "city_turn_se",
  "base",
  "base",
  "wild_grove",
  "city_turn_sw",
  "city_road_h",
  "city_fullcross",
  "city_road_h",
  "city_road_h",
  "city_road_h"],

  ["poplar_tree",
  "city_road_v",
  "base",
  "base",
  "base",
  "base",
  "wild_grove",
  "cobblestone",
  "wild_grove",
  "pine_grove",
  "base",
  "grass_road_v",
  "oak_tree",
  "wild_grove",
  "tree_grove"],

  ["base",
  "city_road_v",
  "base",
  "poplar_tree",
  "park_trees",
  "poplar_tree",
  "cobblestone",
  "base",
  "cobblestone",
  "willow_tree",
  "wild_grove",
  "grass_road_v",
  "base",
  "base",
  "wild_grove"],

  ["base",
  "city_road_v",
  "base",
  "poplar_tree",
  "grass",
  "grass",
  "wild_grove",
  "cobblestone",
  "cobblestone",
  "oak_tree",
  "oak_tree",
  "grass_tcross_north",
  "grass_road_h",
  "grass_road_h",
  "grass_road_h"],

  ["base",
  "city_turn_sw",
  "city_turn_ne",
  "base",
  "base",
  "willow_tree",
  "wild_grove",
  "willow_tree",
  "wild_grove",
  "oak_tree",
  "base",
  "grass_road_v",
  "base",
  "oak_tree",
  "base"],

  ["base",
  "base",
  "city_road_v",
  "base",
  "base",
  "oak_tree",
  "tree_grove",
  "wild_grove",
  "base",
  "tree_grove",
  "grass_turn_nw",
  "grass_turn_se",
  "willow_tree",
  "pine_grove",
  "wild_grove"],

  ["poplar_tree",
  "base",
  "city_road_v",
  "base",
  "base",
  "willow_tree",
  "base",
  "grass_turn_nw",
  "grass_road_h",
  "grass_road_h",
  "grass_tcross_south",
  "willow_tree",
  "willow_tree",
  "willow_tree",
  "base"],

  ["base",
  "base",
  "city_road_v",
  "base",
  "base",
  "base",
  "base",
  "grass_road_v",
  "tree_grove",
  "pine_grove",
  "grass_road_v",
  "tree_sakura_animated",
  "tree_sakura_animated",
  "tree_sakura_animated",
  "tree_sakura_animated"],

  ["base",
  "base",
  "city_tcross_east",
  "city_road_h",
  "city_road_h",
  "city_road_h",
  "city_road_h",
  "grass_tcross_south",
  "pine_grove",
  "base",
  "grass_road_v",
  "tree_sakura_animated",
  "base",
  "tree_sakura_animated",
  "tree_sakura_animated"],

  ["base",
  "base",
  "city_tcross_north",
  "base",
  "base",
  "base",
  "base",
  "grass_tcross_north",
  "grass_road_h",
  "grass_road_h",
  "grass_fullcross",
  "grass_road_h",
  "grass_road_h",
  "grass_road_h",
  "grass_road_h"],

  ["base",
  "base",
  "city_road_v",
  "base",
  "grass",
  "grass",
  "grass",
  "grass_road_v",
  "pine_grove",
  "base",
  "grass_road_v",
  "tree_sakura_animated",
  "tree_sakura_animated",
  "tree_sakura_animated",
  "tree_sakura_animated"]
]
user.save!

categories_hash =
  [{"id"=>12,
  "building_animation_type"=>"occasional",
  "name"=>"Pavilion of Silence",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"tea_pavilion.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>12,
  "y"=>12},

  {"id"=>13,
  "building_animation_type"=>"occasional",
  "name"=>"Observatory",
  "room_image"=>"gothic_library",
  "room_video"=>"rooms/Gargoyle_cat_licking_paw.mp4",
  "sprite_image"=>"observatory.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>9,
  "y"=>14},

  {"id"=>14,
  "building_animation_type"=>"occasional",
  "name"=>"Thoughtful Apothecary",
  "room_image"=>"gothic_library",
  "room_video"=>"rooms/Gargoyle_cat_licking_paw.mp4",
  "sprite_image"=>"apothecary.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>9,
  "y"=>12},

  {"id"=>17,
  "building_animation_type"=>"occasional",
  "name"=>"Fountain of Mystery",
  "room_image"=>"gothic_library",
  "room_video"=>"rooms/Gargoyle_cat_licking_paw.mp4",
  "sprite_image"=>"cat_fountain2.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>14,
  "y"=>10},

  {"id"=>20,
  "building_animation_type"=>"occasional",
  "name"=>"Botanical Garden",
  "room_image"=>"gothic_library",
  "room_video"=>"rooms/Gargoyle_cat_licking_paw.mp4",
  "sprite_image"=>"greenhouse1.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>10,
  "y"=>8},

  {"id"=>21,
  "building_animation_type"=>"occasional",
  "name"=>"CyberCat Statue",
  "room_image"=>"gothic_library",
  "room_video"=>"rooms/Gargoyle_cat_licking_paw.mp4",
  "sprite_image"=>"robot_statue.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>6,
  "y"=>13},

  {"id"=>24,
  "building_animation_type"=>"occasional",
  "name"=>"Simple Palace",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"cozy_hut2.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>14,
  "y"=>8},

  {"id"=>25,
  "building_animation_type"=>"occasional",
  "name"=>"Glade Palace",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"cozy_hut2.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>12,
  "y"=>8},

  {"id"=>26,
  "building_animation_type"=>"occasional",
  "name"=>"Rustic Retreat",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"cozy_hut.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>12,
  "y"=>6},

  {"id"=>27,
  "building_animation_type"=>"occasional",
  "name"=>"Pine Palace",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"cozy_hut.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>13,
  "y"=>6},

  {"id"=>28,
  "building_animation_type"=>"occasional",
  "name"=>"Electric Dreams",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"server_house2_animated.gif",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>3,
  "y"=>14},

  {"id"=>31,
  "building_animation_type"=>"occasional",
  "name"=>"Tower of Typescript",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"hacker_tower3_animated.gif",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>5,
  "y"=>13},

  {"id"=>33,
  "building_animation_type"=>"occasional",
  "name"=>"Matrix Town",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"hacker_tower2.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>5,
  "y"=>11},

  {"id"=>34,
  "building_animation_type"=>"occasional",
  "name"=>"Bank Business",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"finance4.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>6,
  "y"=>10},

  {"id"=>35,
  "building_animation_type"=>"occasional",
  "name"=>"House of Python",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"server_house1.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>4,
  "y"=>13},

  {"id"=>40,
  "building_animation_type"=>"occasional",
  "name"=>"My House and Home",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"brick_apartment1.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>0,
  "y"=>0},

  {"id"=>41,
  "building_animation_type"=>"occasional",
  "name"=>"Hacker Tower",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"hacker_tower.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>3,
  "y"=>13},

  {"id"=>43,
  "building_animation_type"=>"occasional",
  "name"=>"Personal Finances",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"finance1.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>0,
  "y"=>14},

  {"id"=>45,
  "building_animation_type"=>"occasional",
  "name"=>"Mortgage Masion",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"finance2.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>0,
  "y"=>13},

  {"id"=>46,
  "building_animation_type"=>"occasional",
  "name"=>"Wall Street",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"finance1.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>0,
  "y"=>12},

  {"id"=>50,
  "building_animation_type"=>"occasional",
  "name"=>"Main Street Economics",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"finance4.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>1,
  "y"=>14},

  {"id"=>51,
  "building_animation_type"=>"occasional",
  "name"=>"Savings for Pension",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"finance3.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>1,
  "y"=>13},

  {"id"=>52,
  "building_animation_type"=>"occasional",
  "name"=>"Saving for Holidays",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"finance4.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>1,
  "y"=>12},

  {"id"=>53,
  "building_animation_type"=>"occasional",
  "name"=>"Mechanics and Machinery",
  "room_image"=>"gothic_library",
  "room_video"=>"rooms/Gargoyle_cat_licking_paw.mp4",
  "sprite_image"=>"clock_tower_animated.gif",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>3,
  "y"=>1},

  {"id"=>54,
  "building_animation_type"=>"occasional",
  "name"=>"Gargoyle Cat",
  "room_image"=>"gothic_library",
  "room_video"=>"rooms/Gargoyle_cat_licking_paw.mp4",
  "sprite_image"=>"gargoyle_statue.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>3,
  "y"=>3},

  {"id"=>57,
  "building_animation_type"=>"occasional",
  "name"=>"Cozy House",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"brick_apartment4.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>5,
  "y"=>0},

  {"id"=>58,
  "building_animation_type"=>"occasional",
  "name"=>"Interior Decoration",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"brick_apartment1.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>5,
  "y"=>1},

  {"id"=>59,
  "building_animation_type"=>"occasional",
  "name"=>"Favorite Coffees",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"coffee_shop1.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>6,
  "y"=>1},

  {"id"=>60,
  "building_animation_type"=>"occasional",
  "name"=>"Gathering Places",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"brick_apartment3.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>7,
  "y"=>0},

  {"id"=>61,
  "building_animation_type"=>"occasional",
  "name"=>"Places to Visit",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"brick_apartment2.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>7,
  "y"=>1},

  {"id"=>65,
  "building_animation_type"=>"occasional",
  "name"=>"PostresSQL Elephants",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"server_house1.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>3,
  "y"=>11},

  {"id"=>67,
  "building_animation_type"=>"occasional",
  "name"=>"Tower of Wasting Money",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"finance2.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>0,
  "y"=>11},

  {"id"=>68,
  "building_animation_type"=>"occasional",
  "name"=>"Nested and Recursive Functions",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"hacker_tower2.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>1,
  "y"=>11},

  {"id"=>69,
  "building_animation_type"=>"occasional",
  "name"=>"Things I Want to Buy",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"finance4.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>1,
  "y"=>10},

  {"id"=>70,
  "building_animation_type"=>"occasional",
  "name"=>"Hack the Block",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"hacker_tower.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>0,
  "y"=>9},

  {"id"=>72,
  "building_animation_type"=>"occasional",
  "name"=>"Macroeconimics",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"finance1.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>0,
  "y"=>8},

  {"id"=>79,
  "building_animation_type"=>"occasional",
  "name"=>"European Architecture",
  "room_image"=>"gothic_library",
  "room_video"=>"rooms/Gargoyle_cat_licking_paw.mp4",
  "sprite_image"=>"gothic_library.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>7,
  "y"=>4},

  {"id"=>80,
  "building_animation_type"=>"occasional",
  "name"=>"Maneki Fountain",
  "room_image"=>"gothic_library",
  "room_video"=>"rooms/Gargoyle_cat_licking_paw.mp4",
  "sprite_image"=>"cat_fountain1_animated.gif",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>7,
  "y"=>6},

  {"id"=>81,
  "building_animation_type"=>"occasional",
  "name"=>"Long Distant Friends",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"brick_apartment4.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>6,
  "y"=>3},

  {"id"=>82,
  "building_animation_type"=>"occasional",
  "name"=>"SQL Maze",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"server_house2_animated.gif",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>1,
  "y"=>9},

  {"id"=>83,
  "building_animation_type"=>"occasional",
  "name"=>"Wolf of NoteStreet",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"finance1.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>3,
  "y"=>9},

  {"id"=>84,
  "building_animation_type"=>"occasional",
  "name"=>"Budgets for Beginers",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"finance4.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>3,
  "y"=>10},

  {"id"=>85,
  "building_animation_type"=>"occasional",
  "name"=>"Useless Things I Buy",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"finance3.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>4,
  "y"=>11},

  {"id"=>86,
  "building_animation_type"=>"occasional",
  "name"=>"My Buddy House",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"brick_apartment3.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>6,
  "y"=>4},

  {"id"=>88,
  "building_animation_type"=>"occasional",
  "name"=>"Places I Chill",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"cozy_hut2.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>10,
  "y"=>5},

  {"id"=>89,
  "building_animation_type"=>"occasional",
  "name"=>"School Stuff",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"brick_apartment2.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>2,
  "y"=>5},

  {"id"=>90,
  "building_animation_type"=>"occasional",
  "name"=>"University Stuff",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"brick_apartment1.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>3,
  "y"=>5},

  {"id"=>91,
  "building_animation_type"=>"occasional",
  "name"=>"My Other Home",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"convini1.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>5,
  "y"=>5},

  {"id"=>92,
  "building_animation_type"=>"occasional",
  "name"=>"New Apartments",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"brick_apartment4.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>4,
  "y"=>5},

  {"id"=>93,
  "building_animation_type"=>"occasional",
  "name"=>"My Friends House",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"brick_apartment2.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>9,
  "y"=>0},

  {"id"=>94,
  "building_animation_type"=>"occasional",
  "name"=>"Cathedrals",
  "room_image"=>"gothic_library",
  "room_video"=>"rooms/Gargoyle_cat_licking_paw.mp4",
  "sprite_image"=>"gothic_library2.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>0,
  "y"=>4},

  {"id"=>96,
  "building_animation_type"=>"occasional",
  "name"=>"Music Collections",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"brick_apartment3.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>0,
  "y"=>2},

  {"id"=>97,
  "building_animation_type"=>"occasional",
  "name"=>"Get Rich Quick Schemes",
  "room_image"=>nil,
  "room_video"=>nil,
  "sprite_image"=>"server_house1.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>4,
  "y"=>9},

  {"id"=>98,
  "building_animation_type"=>"occasional",
  "name"=>"My Out Kitchen",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"convini1.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>0,
  "y"=>7},

  {"id"=>100,
  "building_animation_type"=>"occasional",
  "name"=>"Tallest Viewing Platforms",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"hacker_tower2.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>10,
  "y"=>3},

  {"id"=>101,
  "building_animation_type"=>"occasional",
  "name"=>"Movie House",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"brick_apartment3.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>9,
  "y"=>1},

  {"id"=>102,
  "building_animation_type"=>"occasional",
  "name"=>"Best Ramen",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"ramen_train_animated.gif",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>12,
  "y"=>3},

  {"id"=>103,
  "building_animation_type"=>"occasional",
  "name"=>"Machine Learning for Cats",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"hacker_tower3_animated.gif",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>14,
  "y"=>3},

  {"id"=>104,
  "building_animation_type"=>"occasional",
  "name"=>"Pets and Places",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"brick_apartment3.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>0,
  "y"=>6},

  {"id"=>105,
  "building_animation_type"=>"occasional",
  "name"=>"Best Teas",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"coffee_shop2.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>2,
  "y"=>7},

  {"id"=>106,
  "building_animation_type"=>"occasional",
  "name"=>"Family Vaccations",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"brick_apartment1.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>3,
  "y"=>8},

  {"id"=>107,
  "building_animation_type"=>"occasional",
  "name"=>"Getaways",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"brick_apartment3.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>4,
  "y"=>8},

  {"id"=>108,
  "building_animation_type"=>"occasional",
  "name"=>"Severville",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"server_house1.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>10,
  "y"=>2},

  {"id"=>109,
  "building_animation_type"=>"occasional",
  "name"=>"Finance Gurus",
  "room_image"=>nil,
  "room_video"=>nil,
  "sprite_image"=>"finance4.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>10,
  "y"=>1},

  {"id"=>111,
  "building_animation_type"=>"occasional",
  "name"=>"Coworkers",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"brick_apartment1.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>2,
  "y"=>6},

  {"id"=>112,
  "building_animation_type"=>"occasional",
  "name"=>"How to Cash a Check",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"finance1.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>10,
  "y"=>0},

  {"id"=>113,
  "building_animation_type"=>"occasional",
  "name"=>"Ruby Methods",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"server_house2_animated.gif",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>14,
  "y"=>0},

  {"id"=>114,
  "building_animation_type"=>"occasional",
  "name"=>"Saving Money Tips",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"finance1.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>12,
  "y"=>2},

  {"id"=>116,
  "building_animation_type"=>"occasional",
  "name"=>"Famous Hackatons",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"hacker_tower.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>13,
  "y"=>0},

  {"id"=>119,
  "building_animation_type"=>"occasional",
  "name"=>"Freelance Gigs",
  "room_image"=>nil,
  "room_video"=>nil,
  "sprite_image"=>"server_house1.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>14,
  "y"=>2},

  {"id"=>120,
  "building_animation_type"=>"occasional",
  "name"=>"Database Books",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"finance2.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>13,
  "y"=>2},

  {"id"=>121,
  "building_animation_type"=>"occasional",
  "name"=>"Full Stack Tower",
  "room_image"=>"hackercat_room",
  "room_video"=>"rooms/Cat_paws_at_laptop_keyboard.mp4",
  "sprite_image"=>"hacker_tower3_animated.gif",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>12,
  "y"=>0},

  {"id"=>123,
  "building_animation_type"=>"occasional",
  "name"=>"Niyazaki Hayao",
  "room_image"=>"cozy_study",
  "room_video"=>"rooms/Cat_waking_up_on_couch.mp4",
  "sprite_image"=>"cat_cafe_animated.gif",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>8,
  "y"=>9},

  {"id"=>124,
  "building_animation_type"=>"occasional",
  "name"=>"SphinxCat",
  "room_image"=>nil,
  "room_video"=>nil,
  "sprite_image"=>"robot_statue.png",
  "summary"=>nil,
  "user_id"=>3,
  "x"=>6,
  "y"=>11}
]

categories_hash.each do |category_hash|
  Category.create!(
    name: category_hash["name"],
    building_animation_type: category_hash["building_animation_type"],
    room_image: category_hash["room_image"],
    room_video: category_hash["room_video"],
    sprite_image: category_hash["sprite_image"],
    x: category_hash["x"],
    y: category_hash["y"],
    user: User.first # Assuming a user was already created previously
  )
end

puts "Successfully seeded user and full city map with hotspots and notes!"
